[project]
name = "file"
version = "0.1.0"
description = "Shared I/O and Database clients"
dependencies = [
    "fsspec",
    "polars",
    "charset-normalizer",
    "xmltodict",
    "s3fs",
    "adlfs",
    "gcsfs",
    "universal-pathlib",
]
requires-python = ">=3.11"

[tool.setuptools]
packages = ["file"]
package-dir = { "file" = "." }

[tool.setuptools.package-data]
"*" = ["py.typed"]
