DROP VIEW IF EXISTS META.CURRENT_EXECUTION;
CREATE VIEW META.CURRENT_EXECUTION AS 

WITH dates AS (
    SELECT
        8 AS OFFSET_HOURS
        , now64(3) + INTERVAL OFFSET_HOURS HOUR AS NOW_TS_LC
        , toDate(NOW_TS_LC) AS TODAY_LC
        , toStartOfDay(NOW_TS_LC) AS TODAY_START_LC
) 
, published_runs AS (
    SELECT 
        RUN_ID
        , JOB_ID
        , DATASET_ID
        , toString(PARTITION_DATE) AS PARTITION_DATE
        , SCHEDULED_TIMESTAMP_LC
        , START_TIMESTAMP_LC
        , END_TIMESTAMP_LC
        , LAST_UPDATED_AT_TS_LC
        , JOB_STATUS
        , CURRENT_STAGE
        , JOB_BITMASK
        , IS_SCHEDULED
        , RUNTIME_OVERRIDES
        , RETRY_ATTEMPTS
        , WATCH_FILE_PATH
        , REMARKS
        , cron_next(if(empty(S.CRON_EXPR), '0 0 * * *', S.CRON_EXPR), SCHEDULED_TIMESTAMP_LC) AS EXPIRATION_THRESHOLD
        , S.IS_SNAPSHOT
    FROM META.EXECUTION_LOG
    LEFT ANY JOIN (
        SELECT JOB_ID, DATASET_ID, IS_SNAPSHOT, CRON_EXPR 
        FROM META.JOB_SCHEDULES 
        LIMIT 1 BY JOB_ID, DATASET_ID
    ) S ON META.EXECUTION_LOG.JOB_ID = S.JOB_ID AND META.EXECUTION_LOG.DATASET_ID = S.DATASET_ID
    WHERE toDate(SCHEDULED_TIMESTAMP_LC) = (SELECT TODAY_LC FROM dates)
    
    LIMIT 1 BY RUN_ID
)

SELECT *
FROM (
    SELECT *
    FROM published_runs

    UNION ALL

    SELECT 
        NULL AS RUN_ID
        , JOB_ID
        , DATASET_ID
        , NULL AS PARTITION_DATE 
        , NEXT_RUN_TS_LC AS SCHEDULED_TIMESTAMP_LC
        , NULL AS START_TIMESTAMP_LC
        , NULL AS END_TIMESTAMP_LC
        , LAST_UPDATED_AT_TS_LC
        , 'PENDING' AS JOB_STATUS
        , NULL AS CURRENT_STAGE
        , NULL AS JOB_BITMASK
        , 1 AS IS_SCHEDULED
        , NULL AS RUNTIME_OVERRIDES
        , 0 AS RETRY_ATTEMPTS
        , WATCH_FILE_PATH
        , NULL AS REMARKS
        , cron_next(if(empty(S.CRON_EXPR), '0 0 * * *', S.CRON_EXPR), NEXT_RUN_TS_LC) AS EXPIRATION_THRESHOLD
        , S.IS_SNAPSHOT
    FROM META.CURRENT_SCHEDULES
    LEFT ANY JOIN (
        SELECT JOB_ID, DATASET_ID, IS_SNAPSHOT, CRON_EXPR 
        FROM META.JOB_SCHEDULES 
        LIMIT 1 BY JOB_ID, DATASET_ID
    ) S ON META.CURRENT_SCHEDULES.JOB_ID = S.JOB_ID AND META.CURRENT_SCHEDULES.DATASET_ID = S.DATASET_ID
    WHERE toDate(SCHEDULED_TIMESTAMP_LC) = (SELECT TODAY_LC FROM dates)
    -- Anti-join: Only show if this specific slot hasn't been pushed to the log yet
    AND (JOB_ID, DATASET_ID, NEXT_RUN_TS_LC) NOT IN (
        SELECT JOB_ID, DATASET_ID, SCHEDULED_TIMESTAMP_LC 
        FROM published_runs
    )
)
ORDER BY SCHEDULED_TIMESTAMP_LC ASC;