DROP VIEW IF EXISTS META.EXECUTION_HISTORY_MV;
CREATE MATERIALIZED VIEW META.EXECUTION_HISTORY_MV 
REFRESH EVERY 1 DAY OFFSET 16 HOUR -- refresh at 12:00 AM UTC+0 every day, adjust offset as needed for different timezones
APPEND TO META.EXECUTION_HISTORY 
AS
WITH dates AS (
    SELECT
        now64(3) + INTERVAL 8 HOUR AS NOW_TS_LC
        , toDate(NOW_TS_LC) AS TODAY_LC
) 
SELECT
    EL.RUN_ID AS RUN_ID
    , EL.JOB_ID AS JOB_ID
    , EL.DATASET_ID AS DATASET_ID
    , toDate(EL.PARTITION_DATE) AS PARTITION_DATE
    , EL.START_TIMESTAMP_LC AS START_TIMESTAMP_LC
    , EL.END_TIMESTAMP_LC AS END_TIMESTAMP_LC
    , EL.LAST_UPDATED_AT_TS_LC AS LAST_UPDATED_AT_TS_LC
    , EL.JOB_STATUS AS JOB_STATUS
    , EL.SOURCE_ROW_COUNT AS SOURCE_ROW_COUNT
    , EL.FINAL_ROW_COUNT AS FINAL_ROW_COUNT
    , EL.FINAL_MANIFEST AS FINAL_MANIFEST
    , EL.REMARKS AS REMARKS
FROM META.EXECUTION_LOG EL
WHERE toDate(LAST_UPDATED_AT_TS_LC) = (SELECT TODAY_LC FROM dates)
ORDER BY RUN_ID, LAST_UPDATED_AT_TS_LC DESC
LIMIT 1 BY RUN_ID;