CREATE MATERIALIZED VIEW IF NOT EXISTS META.EXECUTION_HISTORY_MV 
TO META.EXECUTION_HISTORY AS
SELECT
    RUN_ID
    , JOB_ID
    , DATASET_ID
    , RUN_DATE
    , START_TIMESTAMP
    , END_TIMESTAMP
    , JOB_STATUS
    , SOURCE_ROW_COUNT
    , FINAL_ROW_COUNT
    , FINAL_MANIFEST
FROM META.EXECUTION_LOG
WHERE JOB_STATUS IN ('SUCCESS', 'FAILED', 'EXPIRED');