DROP VIEW IF EXISTS META.EXECUTION_HISTORY_MV;
CREATE MATERIALIZED VIEW META.EXECUTION_HISTORY_MV 
REFRESH EVERY 1 DAY OFFSET 16 HOUR -- refresh at 12:00 AM UTC+0 every day, adjust offset as needed for different timezones
TO META.EXECUTION_HISTORY 
AS
SELECT
    RUN_ID
    , JOB_ID
    , DATASET_ID
    , toDate(PARTITION_DATE) AS PARTITION_DATE
    , START_TIMESTAMP
    , END_TIMESTAMP
    , JOB_STATUS
    , SOURCE_ROW_COUNT
    , FINAL_ROW_COUNT
    , FINAL_MANIFEST
FROM META.EXECUTION_LOG
WHERE JOB_STATUS IN ('SUCCESS', 'FAILED', 'EXPIRED')
  AND toDate(LAST_UPDATED_AT_TS) = today();