-- This Materialized View acts as the "Cron Engine"
-- It runs every minute and pushes 'DUE' jobs into the execution log.
-- SYSTEM STOP REFRESHES META.WORK_QUEUE_TRIGGER_MV;
DROP VIEW IF EXISTS META.WORK_QUEUE_TRIGGER_MV;
CREATE MATERIALIZED VIEW META.WORK_QUEUE_TRIGGER_MV
REFRESH EVERY 1 MINUTE
TO META.EXECUTION_LOG
AS
SELECT
    CAST(NULL, 'Nullable(FixedString(22))') AS RUN_ID
    , JOB_ID
    , DATASET_ID
    , CAST(NULL, 'Nullable(Date)') AS RUN_DATE
    , NEXT_RUN_TS AS SCHEDULED_TIMESTAMP
    , CAST('PENDING', 'LowCardinality(String)') AS JOB_STATUS
    , CAST(NULL, 'LowCardinality(Nullable(String))') AS CURRENT_STEP
    , CAST(0, 'UInt16') AS JOB_BITMASK
FROM META.CURRENT_SCHEDULES
WHERE IS_DUE = 1;

-- SYSTEM RESUME REFRESHES META.WORK_QUEUE_TRIGGER_MV;