-- This Materialized View acts as the "Cron Engine"
-- It runs every minute and pushes 'DUE' jobs into the execution log.

DROP VIEW IF EXISTS META.WORK_QUEUE_TRIGGER_MV;
CREATE MATERIALIZED VIEW META.WORK_QUEUE_TRIGGER_MV
REFRESH EVERY 1 MINUTE
TO META.EXECUTION_LOG
AS
WITH dates AS (
    SELECT
        8 AS OFFSET_HOURS
        , now64(3) + INTERVAL OFFSET_HOURS HOUR AS NOW_TS_LC
        , toDate(NOW_TS_LC) AS TODAY_LC
        , toStartOfDay(NOW_TS_LC) AS TODAY_START_LC
) 
SELECT
    -- Unique Run Identifier generated by DB
    -- Deterministic: Base the ID on the slot time, not the generation time.
    concat(
        formatDateTime(NEXT_RUN_TS_LC, '%Y%m%d-%H%i%s'), 
        '-', 
        substring(lower(hex(MD5(toString(generateUUIDv4())))), 1, 7)
    ) AS RUN_ID
    , JOB_ID
    , DATASET_ID
    , cast(NULL, 'Nullable(Date)') AS PARTITION_DATE
    , NEXT_RUN_TS_LC AS SCHEDULED_TIMESTAMP_LC
    , cast(NULL, 'Nullable(DateTime64(3))') AS START_TIMESTAMP_LC
    , cast(NULL, 'Nullable(DateTime64(3))') AS END_TIMESTAMP_LC
    , (SELECT NOW_TS_LC FROM dates) AS LAST_UPDATED_AT_TS_LC
    , cast(
        if(S.IS_SNAPSHOT = 1 AND LAST_UPDATED_AT_TS_LC > cron_next(if(empty(S.CRON_EXPR), '0 0 * * *', S.CRON_EXPR), NEXT_RUN_TS_LC), 
            'EXPIRED', 
            'PENDING'
        ), 'LowCardinality(String)'
    ) AS JOB_STATUS
    , cast(NULL, 'LowCardinality(Nullable(String))') AS CURRENT_STEP
    , cast(0, 'UInt16') AS JOB_BITMASK 
    , cast(1, 'UInt8') AS IS_SCHEDULED
    , WATCH_FILE_PATH
    , cast(NULL, 'Nullable(String)') AS RUNTIME_OVERRIDES
    , cast(0, 'UInt8') AS RETRY_ATTEMPTS
    , cast(NULL, 'Nullable(UInt64)') AS SOURCE_ROW_COUNT
    , cast(NULL, 'Nullable(UInt64)') AS FINAL_ROW_COUNT
    , cast(NULL, 'Nullable(String)') AS FINAL_MANIFEST
    , cast(NULL, 'Nullable(String)') AS REMARKS
FROM META.CURRENT_SCHEDULES
LEFT ANY JOIN (
    SELECT JOB_ID, DATASET_ID, IS_SNAPSHOT, CRON_EXPR 
    FROM META.JOB_SCHEDULES 
    LIMIT 1 BY JOB_ID, DATASET_ID
) S ON META.CURRENT_SCHEDULES.JOB_ID = S.JOB_ID AND META.CURRENT_SCHEDULES.DATASET_ID = S.DATASET_ID
WHERE IS_DUE = 1;

-- SYSTEM RESUME REFRESHES META.WORK_QUEUE_TRIGGER_MV;