
CREATE OR REPLACE VIEW META.CURRENT_EXECUTION AS
SELECT 
    RUN_ID
    , JOB_ID
    , DATASET_ID
    , RUN_DATE
    , SCHEDULED_TIMESTAMP
    , START_TIMESTAMP
    , END_TIMESTAMP
    , LAST_UPDATED_AT_TS
    , JOB_STATUS
    , CURRENT_STEP
    , JOB_BITMASK
    , WATCH_FILE_PATH
    , RUNTIME_OVERRIDES
    , RETRY_ATTEMPTS
FROM META.EXECUTION_LOG
WHERE toDate(SCHEDULED_TIMESTAMP) == CURRENT_DATE() 
ORDER BY LAST_UPDATED_AT_TS DESC
LIMIT 1 BY RUN_ID;