[project]
name = "ingestion"
version = "0.1.0"
description = "Data Ingestion Service"
dependencies = [
    "auth", # Depends on libs/auth
    "clients", # Depends on libs/clients
    "file", # Depends on libs/file
    "resilience", # Depends on libs/resilience
    "utils", # Depends on libs/utils
    "database", # Depends on libs/database
    "storage", # Depends on libs/storage
    "queue", # Depends on libs/queue
    "network", # Depends on libs/network
    "ray[default]==2.48.0", # 2.39.0
    "polars",
    "pandas", # Required by Ray Data
    "pyarrow",
    "msgspec",
    "nanoid",
    "typer",
    "filelock",
    "dynaconf",
    "apscheduler",
    "diskcache"
]
requires-python = ">=3.11"

[tool.uv.sources]
# This tells uv: "Don't look on PyPI, look inside this monorepo"
auth = { workspace = true }
clients = { workspace = true }
database = { workspace = true }
file = { workspace = true }
resilience = { workspace = true }
utils = { workspace = true }
storage = { workspace = true }
queue = { workspace = true }
network = { workspace = true }
