services:
  clickhouse:
    # container_name: clickhouse-dev
    # image: clickhouse/clickhouse-server:latest
    build:
      context: ./clickhouse
      dockerfile: Dockerfile
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-password}
      - CH_HOST=localhost
      - LOCALSTACK_HOST=localstack
    volumes:
      - ../../../sql:/sql
      - ./clickhouse/clickhouse_settings.xml:/etc/clickhouse-server/config.d/clickhouse_settings.xml
      - ./clickhouse/cron_next_function.xml:/etc/clickhouse-server/cron_next_function.xml
      - ./clickhouse/udf:/var/lib/clickhouse/user_scripts:ro
      # Named volume touse the native Linux filesystem (ext4) inside the Docker VM that supports RENAME_EXCHANGE operation
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"
      - "${CLICKHOUSE_NATIVE_PORT:-9000}:9000"
    ulimits:       
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_ntw

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.tmp/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - ch_ntw

  grafana:
    # image: grafana/grafana:latest
    build:
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./.tmp/grafana:/var/lib/grafana
    networks:
      - ch_ntw

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"            # LocalStack Edge Proxy
    environment:
      - SERVICES=s3,secretsmanager,sts,logs,cloudwatch
      - ACTIVATE_PRO=${ACTIVATE_PRO:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - LANDING_ZONE_BUCKET=${LANDING_ZONE_BUCKET:-landing-zone}
      - ARCHIVE_VAULT_BUCKET=${ARCHIVE_VAULT_BUCKET:-archive-vault}
      - CAS_VAULT_BUCKET=${CAS_VAULT_BUCKET:-cas-vault}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.tmp/localstack:/var/lib/localstack"
      - "./localstack:/etc/localstack/init/ready.d" # Mount the init scripts
    networks:
      - ch_ntw

volumes:
  clickhouse_data:

networks:
  ch_ntw:
    driver: bridge
