CREATE TABLE IF NOT EXISTS EXECUTION_HISTORY(
    RUN_ID                  CHAR(22) ,
    JOB_ID                  VARCHAR(50),
    TARGET_IDENTIFIER       VARCHAR(200),
    JOB_STATUS              VARCHAR(50),
    SOURCE_ROW_COUNT        INTEGER,
    FINAL_ROW_COUNT         INTEGER,
    START_TIMESTAMP         TIMESTAMP_LTZ,
    END_TIMESTAMP           TIMESTAMP_LTZ,
    FINAL_MANIFEST            VARIANT,
)


CREATE_TABLE IF NOT EXIST EXECUTION_LOG (
    RUN_ID                  CHAR(22)
    , JOB_ID                VARCHAR(50) REFERENCES JOB_SCHEDULES(JOB_ID)
    , TARGET_IDENTIFIER     VARCHAR(500)
    , SCHEDULED_TIMESTAMP   TIMESTAMP_LTZ
    , START_TIMESTAMP       TIMESTAMP_LTZ
    , END_TIMESTAMP         TIMESTAMP_LTZ
    , LAST_UPDATED_AT_TS_LC    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
    , JOB_STATUS            VARCHAR(50)
    , CURRENT_STAGE          VARCHAR(20)
    , PROGRESS           INTEGER DEFAULT 0
    , WATCH_FILE_PATH       VARCHAR(1000)
    , RUNTIME_OVERRIDES     VARIANT
    , RETRY_ATTEMPTS        INTEGER DEFAULT 0
    , SOURCE_ROW_COUNT      INTEGER
    , FINAL_ROW_COUNT       INTEGER
    , FINAL_MANIFEST        VARIANT
)

CREATE_TABLE IF NOT EXIST ERROR_LOG (
    RUN_ID                  CHAR(22)
    , JOB_ID                VARCHAR(50)
    , TARGET_IDENTIFIER     VARCHAR(500)
    , STEP_FAILED           VARCHAR(20)
    , ERROR_TYPE            VARCHAR(50)
    , ERROR_MSG             VARCHAR(1000)
    , ERROR_TRACE           VARCHAR(16777216)
    , ERROR_TS             TIMESTAMP_LTZ
)
