CREATE TABLE IF NOT EXIST DEFAULT.EXECUTION_LOG (
    RUN_ID                  CHAR(22) PRIMARY KEY
    , JOB_ID                VARCHAR(50) REFERENCES JOB_SCHEDULES(JOB_ID)
    , DATASET_ID            VARCHAR(500)
    , RUN_DATE              DATE
    , SCHEDULED_TIMESTAMP   TIMESTAMP_LTZ   
    , START_TIMESTAMP       TIMESTAMP_LTZ
    , END_TIMESTAMP         TIMESTAMP_LTZ
    , LAST_UPDATED_AT_TS    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
    , JOB_STATUS            VARCHAR(50)
    , CURRENT_STEP          VARCHAR(20)
    , JOB_BITMASK           INTEGER DEFAULT 0
    , WATCH_FILE_PATH       VARCHAR(1000)
    , RUNTIME_OVERRIDES     VARIANT
    , RETRY_ATTEMPTS        INTEGER DEFAULT 0
    , SOURCE_ROW_COUNT      INTEGER
    , FINAL_ROW_COUNT       INTEGER
    , FINAL_MANIFEST        VARIANT
)
ENGINE = MERGETREE
ORDER BY (JOB_ID, RUN_DATE, LAST_UPDATED_AT_TS)
PARTITION BY toYYYYMM(SCHEDULED_TIMESTAMP)
TTL SCHEDULED_TIMESTAMP + INTERVAL 12 MONTH


CREATE OR REPLACE VIEW DEFAULT.CURRENT_EXECUTION AS
SELECT 
    RUN_ID
    , JOB_ID
    , DATASET_ID
    , RUN_DATE
    , SCHEDULED_TIMESTAMP
    , START_TIMESTAMP
    , END_TIMESTAMP
    , LAST_UPDATED_AT_TS
    , JOB_STATUS
    , CURRENT_STEP
    , JOB_BITMASK
    , WATCH_FILE_PATH
    , RUNTIME_OVERRIDES
    , RETRY_ATTEMPTS
FROM EXECUTION_LOG
WHERE toDate(SCHEDULED_TIMESTAMP) == CURRENT_DATE() 
QUALIFY ROW_NUMBER() OVER (PARTITION BY RUN_ID ORDER BY LAST_UPDATED_AT_TS DESC) = 1

CREATE OR REPLACE VIEW DEFAULT.EXECUTION_HISTORY AS
SELECT 
    RUN_ID
    , JOB_ID
    , DATASET_ID
    , RUN_DATE
    , START_TIMESTAMP
    , END_TIMESTAMP
    , JOB_STATUS
    , JOB_BITMASK
    , RUNTIME_OVERRIDES
    , RETRY_ATTEMPTS
    , SOURCE_ROW_COUNT
    , FINAL_ROW_COUNT
    , FINAL_MANIFEST
FROM EXECUTION_LOG
QUALIFY ROW_NUMBER() OVER (PARTITION BY RUN_ID ORDER BY LAST_UPDATED_AT_TS DESC) = 1


CREATE OR REPLACE VIEW DEFAULT.ERROR_LOG AS
WITH run_summaries AS (
    SELECT 
        RUN_ID,
        JOB_ID,
        -- Get the very first time it failed for the 'Error Timestamp'
        MIN(CASE WHEN JOB_STATUS = 'FAILED' THEN LAST_UPDATED_AT_TS END) as ERROR_TIMESTAMP,
        -- Get the current/latest status of this specific run
        argMax(JOB_STATUS, LAST_UPDATED_AT_TS) as LATEST_STATUS,
        -- Get the latest message or manifest from the failure
        argMax(FINAL_MANIFEST, CASE WHEN JOB_STATUS = 'FAILED' THEN LAST_UPDATED_AT_TS END) as ERROR_DETAILS
    FROM execution_log
    GROUP BY RUN_ID, JOB_ID
)
SELECT 
    RUN_ID,
    JOB_ID,
    DATASET_ID,
    RUN_DATE,
    ERROR_TIMESTAMP,
    ERROR_DETAILS,
    -- If the latest state is SUCCESS, it means it was recovered
    CASE 
        WHEN LATEST_STATUS = 'SUCCESS' THEN 1 
        ELSE 0 
    END AS RESOLVED,
    LATEST_STATUS
FROM run_summaries
-- Only include runs that have failed at least once
WHERE ERROR_TIMESTAMP IS NOT NULL;