[project]
name = "database"
version = "0.1.0"
description = "Shared I/O and Database clients"
dependencies = [
    "clickhouse-connect",
    "polars",
    "oracledb",
    "adbc-driver-snowflake",
    "adbc-driver-postgresql",
    "duckdb",
]
requires-python = ">=3.11"

[tool.setuptools]
packages = ["database"]
package-dir = { "database" = "." }
