from datetime import datetime
from typing import Protocol, runtime_checkable


@runtime_checkable
class TaskStateView(Protocol):
    """Clean domain view of task state required by external evaluation components."""

    @property
    def job_id(self) -> str: ...
    @property
    def run_id(self) -> str: ...
    @property
    def dataset_id(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def is_triggered(self) -> bool: ...
    @property
    def is_snapshot(self) -> bool: ...
    @property
    def scheduled_at(self) -> datetime: ...
    @property
    def expiration_threshold(self) -> datetime | None: ...
    @property
    def partition_date(self) -> str | None: ...
    @property
    def current_step(self) -> str | None: ...
