metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"
replication_factor = 1

# Internal RPC port for Garage nodes to communicate. 
# In a cluster, nodes use this to sync metadata and data.
rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "791460bc648395da78cfb08a543856e7e238e9f3f9423d8eb9d2c40b344d06b2" # Required for cluster identity. Use 'openssl rand -hex 32'

bootstrap_peers = []

[s3_api]
# The primary S3 API endpoint.
s3_region = "garage"
api_bind_addr = "[::]:3900"
# api_auth_signature_v2 enabled for maximum compatibility with older S3 SDKs
# api_auth_signature_v2 = true
root_domain = ".s3.garage.localhost"

[s3_web]
# Optional: Allows hosting static websites directly from S3 buckets.
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index= "index.html"


[admin]
# Administration API used for managing users, keys, and bucket layouts.
api_bind_addr = "0.0.0.0:3903"
# For local dev, we disable admin auth or use a simple token
# admin_token = "$(openssl rand -base64 32)"
metrics_token = "$(openssl rand -base64 32)"


# [::]: iPv6 wildcard
# 0.0.0.0: iPv4 wildcard
